{{ config(materialized='table') }}

SELECT 
COUNTY, 
SUM(HOSPITALIZED_COVID_CONFIRMED_PATIENTS) as TOTAL_HOSPITALIZED_COVID_CONFIRMED_PATIENTS, 
SUM(HOSPITALIZED_SUSPECTED_COVID_PATIENTS) as TOTAL_HOSPITALIZED_SUSPECTED_COVID_PATIENTS
FROM COVID19.OPEN_DATA.HOSPITALS_BY_COUNTY
GROUP BY COUNTY